### ISSUE TITLE
2.0版本后期考虑发布ipa安装包吗

### ISSUE THREAD

**Issue by spirytuslove** [hanerx/DComicReborn#1]
大佬现在1.4.15.6版本使用的ios安装包拷贝漫画加载不出来 后期有考虑出个2.0版本的ios安装包可以再集成下拷贝吗

**Comment by hanerx** [comment]
ipa之前是别人帮忙打的，虽然我有mac但是没开发者账号
拷贝是没api接口，我手机升12之后就没成功抓过包，现在缺拷贝的评论接口
最近比较忙也没时间自己去搞虚拟机抓包，如果有现成的接口就能比较快搞完

**Comment by hanerx** [comment]
好消息，action跑通了，有ipa了；拷贝也支持了。坏消息，都没试过能不能用

**Comment by scount7** [comment]
> 好消息，action跑通了，有ipa了；拷贝也支持了。坏消息，都没试过能不能用

坏消息 闪退（我的是证书签名
